name: open-sol-bot
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytest>=8.3.4
  - pre-commit>=4.0.1
  - jupyter>=1.1.1
  - pytest-asyncio>=0.24.0
  - pytest-xprocess=0.18.1
  - py=1.10.0
  - ruff>=0.3.4
  - pip:
    - -e ./app/trading
    - -e ./app/wallet-tracker
    - -e ./app/cache-preloader
    - -e ./app/tg-bot
    - -e ./libs/cache
    - -e ./libs/db
    - -e ./libs/services
    - -e ./libs/yellowstone_grpc
    - -e ./libs/common 